export const ActionTypes = {
    LOAD_QUESTIONS: 'LOAD_QUESTIONS',
    ADD_QUESTION: 'ADD_QUESTION',
    EDIT_QUESTION: 'EDIT_QUESTION',
    SAVE_QUESTION_NOTES: 'SAVE_QUESTION_NOTES',
    DELETE_QUESTION: 'DELETE_QUESTION',
}
